Import major rewrite of arachsys-a2
dnsmirror is reworked to support peers as well as slaves. We just rsync the
CDB file to the slaves as we needn't run tinydns-data repeatedly. dnsconfig
and dnssort are updated to reflect data file move from data to data.local.

We introduce new scripts mailuseradd, mailuserdel and mailpasswd, using
mailconfig in the intended race-free manner via open2().

mailconfig and dnsconfig now have different -s and non -s behaviour. With -s,
they die at the first error; without -s they check the whole input for errors
before dying. This is more useful than continuing after errors, which is very
unsafe behaviour.

The semantics on mailconfig for domains with multiple users are significantly
changed. The -a flag for non-privileged users is removed and replaced with a
new tool maildomains which lists domains with mail configuration belonging to
a given user, or all domains with corresponding users when run as root.

diff --git a/bin/mailpasswd b/bin/mailpasswd
--- a/bin/mailpasswd
+++ b/bin/mailpasswd
@@ -1,32 +1,45 @@
-#!/bin/sh
+#!/bin/perl -w
 
-if [ $# -ne 2 ]; then
-  cat <<EOF >&2
-Usage: mailpasswd IP USERNAME
-EOF
-  exit 1
-fi
+use Arachsys::A2 qw(checkip checkipuser);
+use File::Basename;
+use IPC::Open2;
+use strict;
 
-TMPDIR=${TMPDIR:-/tmp}
-TMPFILE=`mktemp "$TMPDIR/mailpasswd.XXXXXX"` || exit 1
-trap "rm -f -- \"$TMPFILE\"" 0 1 2 15
+my $userpattern = qr/[a-z0-9-=_@][a-z0-9-=_.@]*/;
+my $privileged = $< == 0;
 
-HOSTADDR=$1
-USERNAME=$2
+sub usage() {
+  print STDERR "Usage: $0 IP USERNAME\n";
+  exit 1;
+}
 
-mailconfig -pr -- "$HOSTADDR" >"$TMPFILE" || exit 1
+$SIG{__DIE__} = sub { die "$0: $_[0]"; };
+$SIG{__WARN__} = sub { warn "$0: $_[0]"; };
+$SIG{INT} = $SIG{TERM} = sub { exit 1; };
 
-if ! pcregrep "^\Q$USERNAME\E(:|$)" "$TMPFILE" >/dev/null; then
-  cat <<EOF >&2
-mailpasswd: mail user $USERNAME does not exist for this IP
-EOF
-  exit 1
-fi
+$0 = basename $0;
+usage unless @ARGV == 2;
 
-PASSWORD=`dovecotpw -s PLAIN` || exit 1
-PASSWORD=`echo "$PASSWORD" | sed 's/^{[^}]*}//'` || exit 1
+my $passwdip;
+die "IP address $ARGV[0] is invalid\n"
+  unless $passwdip = checkip $ARGV[0];
+die "IP address $passwdip does not belong to you\n"
+  unless $privileged or checkipuser $passwdip;
 
-( pcregrep -v "^\Q$USERNAME\E(:|$)" <"$TMPFILE"
-  echo "$USERNAME:$PASSWORD" ) | mailconfig -pws -- "$HOSTADDR" || exit 1
+my $username = $ARGV[1];
+die "Invalid username '$username'\n"
+  unless $username =~ /^$userpattern$/;
 
-echo "Mail configuration successfully updated" >&2
+my $password = `dovecotpw -s PLAIN` or exit 1;
+chomp $password; $password =~ s/^{[^}]*}//;
+
+my $pid = open2 \*OUT, \*IN, "/bin/mailconfig -rwp $passwdip";
+while (<OUT>) {
+  if ((split /[:\n]/)[0] eq $username) {
+    print IN "$username:$password\n";
+  } else {
+    print IN $_;
+  }
+}
+close OUT;
+close IN;
diff --git a/bin/mailuseradd b/bin/mailuseradd
--- a/bin/mailuseradd
+++ b/bin/mailuseradd
@@ -1,30 +1,40 @@
-#!/bin/sh
+#!/bin/perl -w
 
-if [ $# -ne 2 ]; then
-  cat <<EOF >&2
-Usage: mailuseradd IP USERNAME
-EOF
-  exit 1
-fi
+use Arachsys::A2 qw(checkip checkipuser);
+use File::Basename;
+use IPC::Open2;
+use strict;
 
-TMPDIR=${TMPDIR:-/tmp}
-TMPFILE=`mktemp "$TMPDIR/mailuseradd.XXXXXX"` || exit 1
-trap "rm -f -- \"$TMPFILE\"" 0 1 2 15
+my $userpattern = qr/[a-z0-9-=_@][a-z0-9-=_.@]*/;
+my $privileged = $< == 0;
 
-HOSTADDR=$1
-USERNAME=$2
+sub usage() {
+  print STDERR "Usage: $0 IP USERNAME\n";
+  exit 1;
+}
 
-mailconfig -pr -- "$HOSTADDR" >"$TMPFILE" || exit 1
+$SIG{__DIE__} = sub { die "$0: $_[0]"; };
+$SIG{__WARN__} = sub { warn "$0: $_[0]"; };
+$SIG{INT} = $SIG{TERM} = sub { exit 1; };
 
-if pcregrep "^\Q$USERNAME\E(:|$)" "$TMPFILE" >/dev/null; then
-  cat <<EOF >&2
-mailuseradd: mail user $USERNAME already exists for this IP
-EOF
-  exit 1
-fi
+$0 = basename $0;
+usage unless @ARGV == 2;
 
-PASSWORD=`dovecotpw -s PLAIN` || exit 1
-PASSWORD=`echo "$PASSWORD" | sed 's/^{[^}]*}//'` || exit 1
-echo "$USERNAME:$PASSWORD" >>"$TMPFILE"
-mailconfig -pws -- "$HOSTADDR" <"$TMPFILE" || exit 1
-echo "Mail configuration successfully updated" >&2
+my $passwdip;
+die "IP address $ARGV[0] is invalid\n"
+  unless $passwdip = checkip $ARGV[0];
+die "IP address $passwdip does not belong to you\n"
+  unless $privileged or checkipuser $passwdip;
+
+my $username = $ARGV[1];
+die "Invalid username '$username'\n"
+  unless $username =~ /^$userpattern$/;
+
+my $password = `dovecotpw -s PLAIN` or exit 1;
+chomp $password; $password =~ s/^{[^}]*}//;
+
+my $pid = open2 \*OUT, \*IN, "/bin/mailconfig -rwp $passwdip";
+print IN $_ while (<OUT>);
+print IN "$username:$password\n";
+close OUT;
+close IN;
diff --git a/bin/mailuserdel b/bin/mailuserdel
--- a/bin/mailuserdel
+++ b/bin/mailuserdel
@@ -1,29 +1,38 @@
-#!/bin/sh
+#!/bin/perl -w
 
-if [ $# -ne 2 ]; then
-  cat <<EOF >&2
-Usage: mailuserdel IP USERNAME
-EOF
-  exit 1
-fi
+use Arachsys::A2 qw(checkip checkipuser);
+use File::Basename;
+use IPC::Open2;
+use strict;
 
-TMPDIR=${TMPDIR:-/tmp}
-TMPFILE=`mktemp "$TMPDIR/mailuserdel.XXXXXX"` || exit 1
-trap "rm -f -- \"$TMPFILE\"" 0 1 2 15
+my $userpattern = qr/[a-z0-9-=_@][a-z0-9-=_.@]*/;
+my $privileged = $< == 0;
 
-HOSTADDR=$1
-USERNAME=$2
+sub usage() {
+  print STDERR "Usage: $0 IP USERNAME\n";
+  exit 1;
+}
 
-mailconfig -pr -- "$HOSTADDR" >"$TMPFILE" || exit 1
+$SIG{__DIE__} = sub { die "$0: $_[0]"; };
+$SIG{__WARN__} = sub { warn "$0: $_[0]"; };
+$SIG{INT} = $SIG{TERM} = sub { exit 1; };
 
-if ! pcregrep "^\Q$USERNAME\E(:|$)" "$TMPFILE" >/dev/null; then
-  cat <<EOF >&2
-mailuserdel: mail user $USERNAME does not exist for this IP
-EOF
-  exit 1
-fi
+$0 = basename $0;
+usage unless @ARGV == 2;
 
-pcregrep -v "^\Q$USERNAME\E(:|$)" <"$TMPFILE" \
-  | mailconfig -pws -- "$HOSTADDR" || exit 1
+my $passwdip;
+die "IP address $ARGV[0] is invalid\n"
+  unless $passwdip = checkip $ARGV[0];
+die "IP address $passwdip does not belong to you\n"
+  unless $privileged or checkipuser $passwdip;
 
-echo "Mail configuration successfully updated" >&2
+my $username = $ARGV[1];
+die "Invalid username '$username'\n"
+  unless $username =~ /^$userpattern$/;
+
+my $pid = open2 \*OUT, \*IN, "/bin/mailconfig -rwp $passwdip";
+while (<OUT>) {
+  print IN $_ unless (split /[:\n]/)[0] eq $username;
+}
+close OUT;
+close IN;
